### ISSUE TITLE
开启了客户端鉴权，在获取配置时如何传递token

### ISSUE THREAD

**Issue by itxq** [polarismesh/polaris-go#208]
开启客户端鉴权后，使用以下代码无法获取到文件内容，如何有效传递token呢
```golang
func TestPolarisConfig(t *testing.T) {
	polarisIp := "127.0.0.1"
	conf := config.NewDefaultConfiguration([]string{polarisIp + ":8091"})
	conf.Config.ConfigConnectorConfig.Addresses = []string{polarisIp + ":8093"}
	configAPI, err := polaris.NewConfigAPIByConfig(conf)

	if err != nil {
		t.Error(err)
		return
	}

	configFile, err1 := configAPI.GetConfigFile(
		"default",
		"default",
		"config.toml",
	)

	if err1 != nil {
		t.Error(err1)
		return
	}
	println("文件内容：", configFile.GetContent())

	changeChan := configFile.AddChangeListenerWithChannel()
	for {
		select {
		case event := <-changeChan:
			println("有新改动：", "\n", event.NewValue)
		}
	}
}
```

**Comment by chuntaojun** [comment]
```yaml
# 配置中心默认配置
config:
  # 类型转化缓存的key数量
  propertiesValueCacheSize: 100
  # 类型转化缓存的过期时间，默认为1分钟
  propertiesValueExpireTime: 60000
  # 本地缓存配置
  localCache:
    #描述: 配置文件持久化到本地开关
    persistEnable: true
    #描述: 配置文件持久化目录，SDK在配置文件变更后，把相关的配置持久化到本地磁盘
    persistDir: ./polaris/backup/config
    #描述: 配置文件写盘失败的最大重试次数
    persistMaxWriteRetry: 1
    #描述: 配置文件从磁盘读取失败的最大重试次数
    persistMaxReadRetry: 0
    #描述: 缓存读写磁盘的重试间隔
    persistRetryInterval: 500ms
    #描述: 远端获取配置文件失败，兜底降级到本地文件缓存
    fallbackToLocalCache: true
  # 连接器配置，默认为北极星服务端
  configConnector:
    id: polaris-config
    connectorType: polaris
    #描述: 访问server的连接协议，SDK会根据协议名称会加载对应的插件
    protocol: polaris
    token: "${这里填写对应用户/用户组的资源访问凭据 token}"
```
